# application config
spring.application.name=Prueba tecnica - Banco Hipotecario

# logging
logging.level.com.fsole.bh=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] [%highlight(%level)] %cyan(%logger{36}) - %msg%n